version: '3.3'
services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: axon_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8090:8080"


  axonserver:
    image: axoniq/axonserver:4.5.6
    hostname: axonserver
    volumes:
      - type: bind
        source: ./axonserver/data
        target: /data
      - type: bind
        source: ./axonserver/events
        target: /eventdata
      - type: bind
        source: ./axonserver/config
        target: /config
        read_only: true
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"


  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 1234
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak_db
      DB_USER: admin
      DB_PASSWORD: 1234
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
      - "-Dkeycloak.migration.file=/tmp/realm.json"
    volumes:
      - type: bind
        source: ./keycloak/realm.json
        target: /tmp/realm.json
        read_only: true
    ports:
      - "8081:8080"

  keycloak-db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.27
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411