version: '3.3'
services:
  db:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8090:8080"


  axonserver:
    image: axoniq/axonserver:4.5.11
    hostname: axonserver
    volumes:
      - type: bind
        source: ./axonserver/data
        target: /data
      - type: bind
        source: ./axonserver/config
        target: /config
        read_only: true
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"


  keycloak:
    image: quay.io/keycloak/keycloak:18.0
    depends_on:
      - keycloak-db
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 1234
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak_db
      DB_USER: admin
      DB_PASSWORD: 1234
    command:
      - "start-dev"
      - "--import-realm"
    volumes:
      - type: bind
        source: ./keycloak/realm.json
        target: /opt/keycloak/data/import/realm.json
        read_only: true
    ports:
      - "8999:8080"

  keycloak-db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.27
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411