spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: userapp
    password: axon
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
  sql:
    init:
      mode: always
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8999/auth/realms/eventsourcing-with-axon
          jwk-set-uri: http://localhost:8999/auth/realms/eventsourcing-with-axon/protocol/openid-connect/certs

logging:
  level:
    ROOT: WARN
    org:
      axonframework.eventhandling.pooled.Coordinator: info
      flywaydb.core.internal.command: info
      springframework.boot: info

axon:
  serializer:
    events: jackson
  eventhandling:
    processors:
      user-unique-key-projector:
        mode: subscribing
