spring:
  application:
    name: grpc-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8999/realms/eventsourcing-with-axon

grpc:
  server:
    security:
      enabled: true
      # certificateChain: classpath:certs/server.crt
      # privateKey: classpath:certs/serverprivate.key
      key-store: classpath:certs/server-keystore.p12
      key-store-password: server

logging:
  level:
    ROOT: info
    org:
      springframework.boot: info