spring:
  application:
    name: grpc-api

grpc:
  server:
    security:
      enabled: true
      certificateChain: classpath:certs/localhost.crt
      privateKey: classpath:certs/localhost.key

logging:
  level:
    ROOT: info
    org:
      springframework.boot: info