spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: userapp
    password: axon
  flyway:
    locations: classpath:db/migration/postgres
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
  sql:
    init:
      mode: always
      platform: postgres

logging:
  level:
    ROOT: WARN
    org:
      axonframework.eventhandling.pooled.Coordinator: info
      flywaydb.core.internal.command: info
      springframework.boot: info

axon:
  serializer:
    events: jackson
  eventhandling:
    processors:
      user-unique-key-projector:
        mode: subscribing
