spring:
  application:
    name: axon-showcase-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/axon_db
    username: admin
    password: 1234
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  sql:
    init:
      mode: always
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/eventsourcing-with-axon
          jwk-set-uri: http://localhost:8081/auth/realms/eventsourcing-with-axon/protocol/openid-connect/certs

app:
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    ROOT: info


axon:
  serializer:
    events: jackson
  eventhandling:
    processors:
      user-unique-key-projector:
        mode: subscribing
      employee-unique-key-projector:
        mode: subscribing
      participant-unique-key-projector:
        mode: subscribing
      participant-auto-creator:
        mode: subscribing