spring:
  application:
    name: websocket-stomp

  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8999/auth/realms/eventsourcing-with-axon
          jwk-set-uri: http://localhost:8999/auth/realms/eventsourcing-with-axon/protocol/openid-connect/certs

app:
  cors:
    allowed-origins: http://localhost:3000

opentracing:
  spring:
    cloud:
      websocket:
        enabled: false

logging:
  level:
    ROOT: info
    org:
      springframework.boot: info
      springframework.web.socket: debug