logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/v2/users/**
        - id: company-service
          uri: http://localhost:8082
          predicates:
            - Path=/v2/companies/**,/v2/employees/**
        - id: project-service
          uri: http://localhost:8083
          predicates:
            - Path=/v2/projects/**,/v2/tasks/**,/v2/participants/**