name: Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  backend:
    name: Build backend with gradle
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew build
  frontend:
    name: Build frontend with npm
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Execute tests
        working-directory: ./frontend
        run: npm test
      - name: Bundle application
        working-directory: ./frontend
        run: npm build
