name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  backend:
    name: Build backend components with gradle
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permissions for gradlew
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Build API Common
        working-directory: ./backend
        run: ./gradlew :apis:common:build
      - name: Build API GraphQL
        working-directory: ./backend
        run: ./gradlew :apis:graphql:build
      - name: Build API gRPC
        working-directory: ./backend
        run: ./gradlew :apis:grpc:build
      - name: Build API REST
        working-directory: ./backend
        run: ./gradlew :apis:rest:build
      - name: Build API RSocket
        working-directory: ./backend
        run: ./gradlew :apis:rsocket:build

      - name: Build services common api
        working-directory: ./backend
        run: ./gradlew :common:api:build
      - name: Build services common application
        working-directory: ./backend
        run: ./gradlew :common:application:build
      
      - name: Build services user api
        working-directory: ./backend
        run: ./gradlew :user:api:build
      - name: Build services user application
        working-directory: ./backend
        run: ./gradlew :user:application:build
      
      - name: Build services company api
        working-directory: ./backend
        run: ./gradlew :company:api:build
      - name: Build services company application
        working-directory: ./backend
        run: ./gradlew :company:application:build
      
      - name: Build services project api
        working-directory: ./backend
        run: ./gradlew :project:api:build
      - name: Build services project application
        working-directory: ./backend
        run: ./gradlew :project:application:build

      - name: Build demo client for gRPC API
        working-directory: ./backend
        run: ./gradlew :clients:grpc:build
      - name: Build demo client for RSocket API
        working-directory: ./backend
        run: ./gradlew :clients:rsocket:build

  frontend:
    name: Build frontend with npm
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Execute tests
        working-directory: ./frontend
        run: npm test
      - name: Bundle application
        working-directory: ./frontend
        run: npm build
